stages:
- name: images
  steps:
  - publishImageConfig:
      dockerfilePath: ./DOCKERFILE
      buildContext: .
      tag: nginxzq
      registry: 127.0.0.1:34891
- name: publish
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
